### ISSUE TITLE
BO Quadrupole QD Model02 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/bo-quadrupoles-qd#1]
Injection (5.7 A):
 bo-quadrupoles-qd/model-02/2017-01-10_BO_QD_Model02_Sim_X=-20_20mm_Z=-300_300mm_Imc=5.7A.txt 

Extraction (113.7 A):
 bo-quadrupoles-qd/model-02/2017-01-10_BO_QD_Model02_Sim_X=-20_20mm_Z=-300_300mm_Imc=113.7A.txt 

Maximum Gradient (119.5 A):
 bo-quadrupoles-qd/model-02/2017-01-10_BO_QD_Model02_Sim_X=-20_20mm_Z=-300_300mm_Imc=119.5A.txt

**Comment by xresende** [comment]
all three fmaps analysed for model 02. maximum integrated quadrupole achieved. relative multipoles are all within specs.
